In [7]:
# Create two matrices using nested lists

matrix1 = [ 
    [1, 2, 3], 
    [4, 5, 6]
]

matrix2 = [ 
    [7, 8, 9],
    [10, 11, 12]
]

# Initialize a result matrix with the same size
result = [ 
    [0, 0, 0],
    [0, 0, 0] 
]
# Perform matrix addition

for i in range(len(matrix1)):                  #loop through rows
    for j in range(len(matrix1[0])):           #loop through columns
        result[i][j] = matrix1[i][j] + matrix2[i][j]
         


# Display the result

print("Matrix 1:")
for row in matrix1:
    print(row)

print("\nMatrix 2:")
for row in matrix2:
    print(row)

print("\nSum of Matrix 1 and Matrix 2:")
for row in result:
    print(row)

Matrix 1:
[1, 2, 3]
[4, 5, 6]

Matrix 2:
[7, 8, 9]
[10, 11, 12]

Sum of Matrix 1 and Matrix 2:
[8, 10, 12]
[14, 16, 18]


In [8]:
#ADDITION OF TWO MATRICES USING ARRAY
import numpy as np
A1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
A2 =np.array([[10,11,12],[13,14,15],[16,17,18]])
A3=A1+A2
print("addition of two matrices")
print(A3)

addition of two matrices
[[11 13 15]
 [17 19 21]
 [23 25 27]]
